apiVersion: apps/v1
kind: Deployment
metadata:
  name: gfytfj99
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gfytfj99
  template:
    metadata:
      labels:
        app: gfytfj99
    spec:
      containers:
      - image: okteto.dev/gfytfj99:latest
        name: gfytfj99
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "4af2eb88-322d-426a-b7b4-3944358d8091"
        - name: Vless_Path
          value: "/vl55fdg5"
        - name: Vmess_UUID
          value: "4af2eb88-322d-426a-b7b4-3944358d8091"
        - name: Vmess_Path
          value: "/vm6dgygh66"
        - name: Share_Path
          value: "/v2link"
